### ISSUE TITLE
monitor fails

### ISSUE THREAD

**Issue by grimm26** [livingsocial/rearview#23]
After having gotten rearview up, I tried adding my first monitor.  Here's the expressions section:

```
puts @timeseries

avg = @a.values.mean
raise "Running #{avg} transactions!" if avg > 1
```

When I hit the test button I get this error output:

```
/home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find i18n-0.6.5 in any of the sources (Bundler::GemNotFound)
    from /home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler/spec_set.rb:85:in `map!'
    from /home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler/spec_set.rb:85:in `materialize'
    from /home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler/definition.rb:133:in `specs'
    from /home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler/definition.rb:178:in `specs_for'
    from /home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler/definition.rb:167:in `requested_specs'
    from /home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler/environment.rb:18:in `requested_specs'
    from /home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler/runtime.rb:13:in `setup'
    from /home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler.rb:119:in `setup'
    from /home/rearview/.rvm/gems/jruby-1.7.10/gems/bundler-1.5.2/lib/bundler/setup.rb:17:in `<top (required)>'
    from /home/rearview/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/rearview/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
```

The gem does seem to be there, but I'm an rvm n00b.

**Comment by talbright** [comment]
The short answer is, all the gems defined in sandbox/Gemfile need to be installed in whichever ruby you defined in the sandbox_exec array. What does your sandbox_exec setting look like?

**Comment by grimm26** [comment]
ah, there we go.  Had to switch rvm to my sandbox ruby, go into sandbox/ and run bundle install.

**Comment by talbright** [comment]
The setup script should do that for you, not sure exactly where things got off track there. Regardless, glad you got it to work.

**Comment by ananthkollipara** [comment]
Hi...am trying to setup my first monitor...i have issue setting it up. Can you please assist?

```
1) Am getting the error: Metrics contains an invalid metric: alias(servers.prod.kodiak-SA3.callfailures, "call_failures")
2) my metrics: alias(servers.prod.kodiak-SA3.callfailures, "call_failures")
3) my expression: call_failures = @a.values.sum
raise "call failures is high !!" if call_failures > 1
4) logs:
I, [2014-04-15T14:48:14.635000 #26992]  INFO -- : Started POST "/monitor.json" for 192.168.15.156 at 2014-04-15 14:48:14 +0530
I, [2014-04-15T14:48:14.642000 #26992]  INFO -- : Processing by Rearview::MonitorController#create as JSON
I, [2014-04-15T14:48:14.643000 #26992]  INFO -- :   Parameters: {"id"=>"", "dashboardId"=>"1", "userId"=>"1", "name"=>"Call Failures", "active"=>"true", "jobType"=>"monitor", "version"=>"2", "cronExpr"=>"0 1 * * * Mon,Tue,Wed,Thu,Fri", "errorTimeout"=>"60", "minutes"=>"1", "metrics"=>["alias(servers.prod.kodiak-SA3.callfailures, \"call_failures\")"], "monitorExpr"=>"puts @timeseries\n\ncall_failures = @a.values.sum\nraise \"call failures is high !!\" if call_failures > 1", "toDate"=>"now", "createdAt"=>"", "modifiedAt"=>"", "description"=>"call failures"}
I, [2014-04-15T14:48:14.678000 #26992]  INFO -- :   Rendered /usr/local/rvm/gems/jruby-1.7.5@rearview/gems/rearview-1.2.0-java/app/views/rearview/monitor/create.json.jbuilder (3.0ms)
I, [2014-04-15T14:48:14.679000 #26992]  INFO -- : Completed 200 OK in 35ms (Views: 7.0ms | ActiveRecord: 1.0ms)

graphite data:
```

[root@kodiak-SA3 gp]# ll -art /iData/whisper/servers/prod/kodiak-SA3/callfailures.wsp
-rwxr-xr-x 1 root root 17308 Apr 15 14:45 /iData/whisper/servers/prod/kodiak-SA3/callfailures.wsp

**Comment by steveakers** [comment]
Try doing a chown carbon:carbon on your whisper directory and all sub-directories and files.

**Comment by ananthkollipara** [comment]
Thanks Steve. However i didn't run this command. I had issues in apache web server. I could see 500 error codes in access_logs. Fixed the apache issue. Will check with you, if i need any further help.

**Comment by ananthkollipara** [comment]
Can you please let me know how to debug -> "firing event :error" ?

```
I, [2014-04-16T15:46:24.139000 #15553]  INFO -- : #<Rearview::ResultsHandler:0x5776dc11> run
D, [2014-04-16T15:46:24.142000 #15553] DEBUG -- :   Rearview::JobData Load (1.0ms)  SELECT `job_data`.* FROM `job_data` WHERE `job_data`.`job_id` = 2 LIMIT 1
D, [2014-04-16T15:46:24.147000 #15553] DEBUG -- :   SQL (1.0ms)  UPDATE `job_data` SET `data` = '{\"status\":\"error\",\"output\":null,\"graph_data\":null}', `updated_at` = '2014-04-16 10:16:24' WHERE `job_data`.`id` = 2
I, [2014-04-16T15:46:24.205000 #15553]  INFO -- : #<Rearview::ResultsHandler:0x5776dc11> firing event :error for #<Rearview::Job id: 2, created_at: "2014-04-16 08:10:18", updated_at: "2014-04-16 10:15:24", name: "POC1 Call Failures", active: true, last_run: "2014-04-16 10:16:24", cron_expr: "0 * * * * ?", status: "error", user_id: 1, alert_keys: [], deleted_at: nil, error_timeout: 60, next_run: nil, description: "", app_id: 1, metrics: ["alias(servers.prod.kodiak-SA2.callfailures, \"call_failures\")"], monitor_expr: "puts @timeseries\n\ncall_failures = @a.values.sum\nrai...", minutes: 1, to_date: "now">
D, [2014-04-16T15:46:24.222000 #15553] DEBUG -- :   SQL (1.0ms)  UPDATE `jobs` SET `last_run` = '2014-04-16 10:16:24', `updated_at` = '2014-04-16 10:16:24', `alert_keys` = '[]', `metrics` = '[\"alias(servers.prod.kodiak-SA2.callfailures, \\\"call_failures\\\")\"]' WHERE `jobs`.`id` = 2
D, [2014-04-16T15:46:24.226000 #15553] DEBUG -- :   Rearview::JobError Load (1.0ms)  SELECT `job_errors`.* FROM `job_errors` WHERE (job_id = 2) ORDER BY created_at DESC LIMIT 1
```

**Comment by ananthkollipara** [comment]
Also do you have a list of defined error codes?

**Comment by ananthkollipara** [comment]
I also see this...

```
I, [2014-04-16T20:06:07.341000 #28040]  INFO -- :   Rendered /usr/local/rvm/gems/jruby-1.7.5@rearview/gems/rearview-1.2.0-java/app/views/rearview/jobs/show.json.jbuilder (11.0ms)
I, [2014-04-16T20:06:07.342000 #28040]  INFO -- : Completed 422 Unprocessable Entity in 95ms (Views: 13.0ms | ActiveRecord: 3.0ms)
I, [2014-04-16T20:06:12.403000 #28040]  INFO -- : Started GET "/jobs/2/data" for 192.168.15.25 at 2014-04-16 20:06:12 +0530
I, [2014-04-16T20:06:12.407000 #28040]  INFO -- : Processing by Rearview::JobsController#data as */*
I, [2014-04-16T20:06:12.408000 #28040]  INFO -- :   Parameters: {"id"=>"2"}
D, [2014-04-16T20:06:12.411000 #28040] DEBUG -- :   Rearview::User Load (1.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` ASC LIMIT 1
D, [2014-04-16T20:06:12.461000 #28040] DEBUG -- :   Rearview::JobData Load (2.0ms)  SELECT `job_data`.* FROM `job_data` WHERE `job_data`.`job_id` = 2 LIMIT 1
I, [2014-04-16T20:06:12.467000 #28040]  INFO -- :   Rendered /usr/local/rvm/gems/jruby-1.7.5@rearview/gems/rearview-1.2.0-java/app/views/rearview/job_data/_job_data.json.jbuilder (0ms)
I, [2014-04-16T20:06:12.467000 #28040]  INFO -- :   Rendered /usr/local/rvm/gems/jruby-1.7.5@rearview/gems/rearview-1.2.0-java/app/views/rearview/jobs/data.json.jbuilder (2.0ms)
I, [2014-04-16T20:06:12.468000 #28040]  INFO -- : Completed 200 OK in 60ms (Views: 6.0ms | ActiveRecord: 3.0ms)
```

**Comment by ananthkollipara** [comment]
am seeing the following issue....any advise...

## firing event :error for

```
I, [2014-04-18T12:20:49.109000 #10879]  INFO -- : #<Rearview::ResultsHandler:0xe244821> run
====>{:status=>"error", :output=>nil, :graph_data=>nil}
I, [2014-04-18T12:20:49.109000 #10879]  INFO -- : {:status=>"error", :output=>nil, :graph_data=>nil}
D, [2014-04-18T12:20:49.119000 #10879] DEBUG -- :   Rearview::JobData Load (1.0ms)  SELECT `job_data`.* FROM `job_data` WHERE `job_data`.`job_id` = 5 LIMIT 1
D, [2014-04-18T12:20:49.126000 #10879] DEBUG -- :   SQL (0ms)  UPDATE `job_data` SET `data` = '{\"status\":\"error\",\"output\":null,\"graph_data\":null}', `updated_at` = '2014-04-18 12:20:49' WHERE `job_data`.`id` = 6
I, [2014-04-18T12:20:49.192000 #10879]  INFO -- : #<Rearview::ResultsHandler:0xe244821> firing event :error for #<Rearview::Job id: 5, created_at: "2014-04-18 11:28:31", updated_at: "2014-04-18 12:19:48", name: "my ABC monitor", active: true, last_run: "2014-04-18 12:20:49", cron_expr: "0 * * * * ?", status: "error", user_id: 1, alert_keys: [], deleted_at: nil, error_timeout: 60, next_run: nil, description: "test 123", app_id: 1, metrics: ["alias(servers.prod.abc, \"abc\")"], monitor_expr: "puts @timeseries\n\nabc = @a.values.sum\ngraph_value[\"...", minutes: 10, to_date: "now">
```
